repos:
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.10
    hooks:
      - id: terraform-fmt
      - id: gofmt
  - repo: local
    hooks:
      - id: update-docs
        name: docs should be up-to-date
        language: system
        pass_filenames: false
        entry: make docs-check
