name: Prepare Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, prd]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare Release
        id: prepare_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_FETCH_PAT }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Test Test
          draft: true
          prerelease: true
