name: Prepare Release

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: [self-hosted, prd]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15'
      - id: get-plain-version
        run: |
          version=$(echo ${{ github.ref }} | cut -c2-)
          echo "::set-output name=version::$version"
      - name: Build release binaries
        run: VERSION="${{steps.get-plain-version.outputs.version}}" make release
      - name: Prepare Release
        id: prepare_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_FETCH_PAT }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Test Test
          draft: true
          prerelease: true
      # TODO: use matrix strategy?
      - name: Add linux binaries to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_FETCH_PAT }}
        with:
          upload_url: ${{ steps.prepare_release.outputs.upload_url }}
          asset_path: ${{ format('./bin/terraform-provider-sonarcloud_{0}_linux_amd64', steps.get-plain-version.outputs.version) }}
          asset_name: ${{ format('terraform-provider-sonarcloud_{0}_linux_amd64', steps.get-plain-version.outputs.version) }}
          asset_content_type: application/octet-stream
      - name: Add mac binaries to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_FETCH_PAT }}
        with:
          upload_url: ${{ steps.prepare_release.outputs.upload_url }}
          asset_path: ${{ format('./bin/terraform-provider-sonarcloud_{0}_darwin_amd64', steps.get-plain-version.outputs.version) }}
          asset_name: ${{ format('terraform-provider-sonarcloud_{0}_darwin_amd64', steps.get-plain-version.outputs.version) }}
          asset_content_type: application/octet-stream
      - name: Add window binaries to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_FETCH_PAT }}
        with:
          upload_url: ${{ steps.prepare_release.outputs.upload_url }}
          asset_path: ${{ format('./bin/terraform-provider-sonarcloud_{0}_windows_amd64', steps.get-plain-version.outputs.version) }}
          asset_name: ${{ format('terraform-provider-sonarcloud_{0}_windows_amd64', steps.get-plain-version.outputs.version) }}
          asset_content_type: application/octet-stream
