name: Prepare Release

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: [self-hosted, prd]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Unshallow
        run: git fetch --prune --unshallow

      - uses: actions/setup-go@v2
        with:
          go-version: '1.15'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@56f5b77f7fa4a8fe068bf22b732ec036cc9bc13f
        with:
          version: latest
          args: release --rm-dist
        env:
          # TODO: add GPG fingerprint
          GITHUB_TOKEN: ${{ secrets.ORG_FETCH_PAT }}
